resources:
- ingress.yaml
- namespace.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- secrets.yaml
- pvc.yaml
- ingress-backend.yaml
- clasign-ingress.yaml
- clasign-secrets.yaml
- clasign-backend.yaml
commonLabels:
  app: infrastructure-cla
commonAnnotations:
  email: chenzeng765@163.com
  owner: chenzeng
namespace: cla
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/cla-backend
  newTag: 646366ea482ef136e36e738e672ce4a9f0c5c2eb
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/cla-robot
  newTag: b24aee5c1a3be0d35369361b68309a9fa5fb8a6b
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/cla-webui
  newTag: 39365d8e5ae5ef4f2150dfa2c8aeaa6eb5f5cfac
