resources:
- web.yaml
- ingress.yaml
- namespace.yaml
- secret.yaml
- mail2list-backend.yaml
- opengaussdb.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mail2list
images:
- name: enmotech/opengauss
  newTag: 2.1.0
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/mail2list/mail-backend
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/mail2list/mail-backend
  newTag: e7a097176dc70aedad258c28f055b6f5785b85c4
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/mail2list/web
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/mail2list/web
  newTag: 5911c02244622e5505d17a554cf2a4516902d047
