apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: mail2list-web-tls
  namespace: mail2list
spec:
  name: mail2list-web-tls
  keysMap:
    ca.crt:
      path: secrets/data/infra-test/mail2list-secrets
      key: server.crt
    tls.crt:
      path: secrets/data/infra-test/mail2list-secrets
      key: server.crt
    tls.key:
      path: secrets/data/infra-test/mail2list-secrets
      key: server.key

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: mail2list-backend-secrets
  namespace: mail2list
spec:
  name: mail2list-backend-secrets
  keysMap:
    openeuguass_user:
      path: secrets/data/infra-test/mail2list-secrets
      key: openeuguass_user
    openeuguass_pwd:
      path: secrets/data/infra-test/mail2list-secrets
      key: openeuguass_pwd
    openeuguass_url:
      path: secrets/data/infra-test/mail2list-secrets
      key: openeuguass_url
    openeuguass_port:
      path: secrets/data/infra-test/mail2list-secrets
      key: openeuguass_port
    openeuguass_database:
      path: secrets/data/infra-test/mail2list-secrets
      key: openeuguass_database
    mine_email:
      path: secrets/data/infra-test/mail2list-secrets
      key: mine_email
    smtp_server:
      path: secrets/data/infra-test/mail2list-secrets
      key: smtp_server
    smtp_password:
      path: secrets/data/infra-test/mail2list-secrets
      key: smtp_password
    imap_server:
      path: secrets/data/infra-test/mail2list-secrets
      key: imap_server
    archive_mine_email:
      path: secrets/data/infra-test/mail2list-secrets
      key: archive_mine_email
    archive_smtp_server:
      path: secrets/data/infra-test/mail2list-secrets
      key: archive_smtp_server
    archive_password:
      path: secrets/data/infra-test/mail2list-secrets
      key: archive_password
    archive_name:
      path: secrets/data/infra-test/mail2list-secrets
      key: archive_name
    archive_imap_server:
      path: secrets/data/infra-test/mail2list-secrets
      key: archive_imap_server
    leave_email:
      path: secrets/data/infra-test/mail2list-secrets
      key: leave_email
    leave_smtp_server:
      path: secrets/data/infra-test/mail2list-secrets
      key: leave_smtp_server
    leave_email_password:
      path: secrets/data/infra-test/mail2list-secrets
      key: leave_email_password
    leave_name:
      path: secrets/data/infra-test/mail2list-secrets
      key: leave_name
    leave_imap_server:
      path: secrets/data/infra-test/mail2list-secrets
      key: leave_imap_server

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: mail2list-gaussdb-secrets
  namespace: mail2list
spec:
  name: mail2list-gaussdb-secrets
  keysMap:
    gs_password:
      path: secrets/data/infra-test/mail2list-secrets
      key: gs_password
    gs_nodename:
      path: secrets/data/infra-test/mail2list-secrets
      key: gs_nodename
    gs_username:
      path: secrets/data/infra-test/mail2list-secrets
      key: gs_username
    gs_port:
      path: secrets/data/infra-test/mail2list-secrets
      key: gs_port

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: mail2list-web-secrets
  namespace: mail2list
spec:
  name: mail2list-web-secrets
  keysMap:
    api_base_url:
      path: secrets/data/infra-test/mail2list-secrets
      key: api_base_url
