resources:
  - ../../../common-services/nginx-ingress
commonLabels:
  app: openeuler-hk-ingress
commonAnnotations:
  owner: tommylike
  email: "tommylikehu@gmail.com"
patchesStrategicMerge:
  - service.yaml
  - deployment.yaml
  - tcp_configmap.yaml
