kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  annotations:
    service.kubernetes.io/tke-existed-lbid: lb-fcpl872f 
spec:
  #We need set this into 'Local' since we need get the client IP of elb.
  externalTrafficPolicy: Local
