resources:
- ingress.yaml
- deployment.yaml
- namespace.yaml
- service.yaml
- secrets.yaml
commonLabels:
  app: moocstudio-openeuler-website-frontend
commonAnnotations:
  owner: Caowendong
namespace: moocstudio-openeuler-website-frontend
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/moocstudio-app
  newTag: 292f4e42cc8385cacf3778f173c9a609ea16aa7e
