resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- secret.yaml
- redis-service.yaml
- redis-statefulset.yaml
namespace: omni-manager-backend
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/omni-manager-backend/omni-manager
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/omni-manager-backend/omni-manager
  newTag: edd6bc009ea90ddc765165b056e299fbc15b3784
