resources:
- analysis.yaml
- dm.yaml
- eureka.yaml
- gateway.yaml
- api-gateway.yaml
- ingress.yaml
- sca-namespace.yaml
- secrets.yaml
- web.yaml
commonLabels:
  server: infrastructure-sca
commonAnnotations:
  email: xzq615@hotmail.com
  owner: xiaozhongqi
namespace: sca
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/sca-analysis
  newTag: a978ef2e63197b1db981d5c66e9c385937a35b0f
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/sca-api-gateway
  newTag: a978ef2e63197b1db981d5c66e9c385937a35b0f
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/sca-datamanager
  newTag: bc9c3cc1ebb3d469c47d3c2eb47bd0ad8c9f863c
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/sca-eureka
  newTag: dc8bc1d89ae17e6a4ba932fde160323475f98342
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/sca-gateway
  newTag: dc8bc1d89ae17e6a4ba932fde160323475f98342
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/sca-web
  newTag: a978ef2e63197b1db981d5c66e9c385937a35b0f
