resources:
- analysis.yaml
- dm.yaml
- eureka.yaml
- gateway.yaml
- api-gateway.yaml
- ingress.yaml
- sca-namespace.yaml
- secrets.yaml
- web.yaml
commonLabels:
  server: infrastructure-sca
commonAnnotations:
  email: xzq615@hotmail.com
  owner: xiaozhongqi
namespace: sca
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/sca-analysis
  newTag: 988d5a18b6268797afec40bb297426c6678a6e74
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/sca-api-gateway
  newTag: 988d5a18b6268797afec40bb297426c6678a6e74
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/sca-datamanager
  newTag: 988d5a18b6268797afec40bb297426c6678a6e74
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/sca-eureka
  newTag: dc8bc1d89ae17e6a4ba932fde160323475f98342
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/sca-gateway
  newTag: dc8bc1d89ae17e6a4ba932fde160323475f98342
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/sca-web
  newTag: 988d5a18b6268797afec40bb297426c6678a6e74
