resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- ingress.yaml
namespace: cvesa-test
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/cve-sa-backend/cvesa-test
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/cve-sa-backend/cvesa-test
  newTag: d7b38a1d1f6362fbb462d288c98c72c154c749c7
