apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
        - args:
            - --provider=oidc
            - --email-domain=*
            - --upstream=http://argocd-server.argocd.svc.cluster.local
            - --http-address=0.0.0.0:4180
            - --provider-display-name=authing
            - --cookie-expire=6h0m0s
            - --redirect-url=https://build.osinfra.cn/oauth2/callback
            - --oidc-issuer-url=https://infra-argocd.authing.cn/oidc
            - --skip-auth-regex=^/api/
            - --insecure-oidc-allow-unverified-email=true
            - --session-cookie-minimal=false
            - --pass-access-token=true
            - --cookie-secure=false
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: client_id
                  name: argocd-notifications-secret
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: client_secret
                  name: argocd-notifications-secret
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  key: cookie_secret
                  name: argocd-notifications-secret
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/oauth2-proxy:4b64a9c04a247dd5da3ff664d9d497c902324c3a
          imagePullPolicy: Always
          name: oauth2-proxy
          ports:
            - containerPort: 4180
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
spec:
  ports:
    - name: http
      port: 4180
      protocol: TCP
      targetPort: 4180
  selector:
    k8s-app: oauth2-proxy

---

#apiVersion: networking.k8s.io/v1beta1
#kind: Ingress
#metadata:
#  name: oauth2-proxy
#spec:
#  rules:
#    - host: build.osinfra.cn
#      http:
#        paths:
#          - backend:
#              serviceName: oauth2-proxy
#              servicePort: 4180
#            path: /oauth2
#  tls:
#    - hosts:
#        - build.osinfra.cn
#      secretName: tls-secrets
