resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- ingress.yaml
- secret.yaml
namespace: openlookeng-indextool
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openlookeng/index-tools-test
  newTag: 4791fd75842579421bbbd5cadf5d7c7bbd819b29
