resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- ingress.yaml
- pvc.yaml
- job.yaml
namespace: mindspore-website
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/mindspore-website-test
  newTag: fa28e81c1bcc6253f0023f6421826c4a7845238f
